# Project information
site_name: Hello 算法
site_url: https://www.hello-algo.com/
site_author: Krahets
site_description: 一本动画图解、能运行、可提问的数据结构与算法入门书
# Repository
repo_name: krahets/hello-algo
repo_url: https://github.com/krahets/hello-algo
edit_uri: https://github.com/krahets/hello-algo/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Krahets

# Configuration
theme:
  name: material
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      # primary: grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/krahets
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/krahets
    - icon: fontawesome/solid/code 
      link: https://leetcode.cn/u/jyd/
  generator: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - 写在前面:
    - index.md
    - 关于本书: chapter_preface/about_the_book.md
    - 如何使用本书: chapter_preface/suggestions.md
    - 小结: chapter_preface/summary.md
  - 算法相关:
    - 引言:
      - 算法无处不在: chapter_about_algorithms/chapter_introduction/algorithms_are_everywhere.md
      - 算法是什么: chapter_about_algorithms/chapter_introduction/what_is_dsa.md
      - 小结: chapter_about_algorithms/chapter_introduction/summary.md
    - 附录:
      - 编程环境安装: chapter_about_algorithms/chapter_appendix/installation.md
      - 一起参与创作: chapter_about_algorithms/chapter_appendix/contribution.md
    - 参考文献:
      - chapter_about_algorithms/chapter_reference/index.md
  - 算法基础:
    - 复杂度分析:
      - 算法效率评估: chapter_base_algorithms/chapter_computational_complexity/performance_evaluation.md
      - 时间复杂度: chapter_base_algorithms/chapter_computational_complexity/time_complexity.md
      - 空间复杂度: chapter_base_algorithms/chapter_computational_complexity/space_complexity.md
      - 权衡时间与空间: chapter_base_algorithms/chapter_computational_complexity/space_time_tradeoff.md
      - 小结: chapter_base_algorithms/chapter_computational_complexity/summary.md
    - 查找算法:
      - 线性查找: chapter_base_algorithms/chapter_searching/linear_search.md
      - 二分查找: chapter_base_algorithms/chapter_searching/binary_search.md
      - 哈希查找: chapter_base_algorithms/chapter_searching/hashing_search.md
      - 小结: chapter_base_algorithms/chapter_searching/summary.md
    - 排序算法:
      - 排序简介: chapter_base_algorithms/chapter_sorting/intro_to_sort.md
      - 冒泡排序: chapter_base_algorithms/chapter_sorting/bubble_sort.md
      - 插入排序: chapter_base_algorithms/chapter_sorting/insertion_sort.md
      - 快速排序: chapter_base_algorithms/chapter_sorting/quick_sort.md
      - 归并排序: chapter_base_algorithms/chapter_sorting/merge_sort.md
      - 小结: chapter_base_algorithms/chapter_sorting/summary.md
  - 数据结构:
    - 简介:
      - 数据与内存: chapter_data_structure/data_and_memory.md
      - 数据结构分类: chapter_data_structure/classification_of_data_structure.md
      - 小结: chapter_data_structure/summary.md
    - 数组与链表:
        - 数组: chapter_data_structure/chapter_array_and_linkedlist/array.md
        - 链表: chapter_data_structure/chapter_array_and_linkedlist/linked_list.md
        - 列表: chapter_data_structure/chapter_array_and_linkedlist/list.md
        - 小结: chapter_data_structure/chapter_array_and_linkedlist/summary.md
    - 栈与队列:
        - 栈: chapter_data_structure/chapter_stack_and_queue/stack.md
        - 队列: chapter_data_structure/chapter_stack_and_queue/queue.md
        - 双向队列: chapter_data_structure/chapter_stack_and_queue/deque.md
        - 小结: chapter_data_structure/chapter_stack_and_queue/summary.md
    - 散列表:
      - 哈希表: chapter_data_structure/chapter_hashing/hash_map.md
      - 哈希冲突处理: chapter_data_structure/chapter_hashing/hash_collision.md
      - 小结: chapter_data_structure/chapter_hashing/summary.md
    - 树:
      - 二叉树: chapter_data_structure/chapter_tree/binary_tree.md
      - 二叉树遍历: chapter_data_structure/chapter_tree/binary_tree_traversal.md
      - 二叉搜索树: chapter_data_structure/chapter_tree/binary_search_tree.md
      - AVL 树 *: chapter_data_structure/chapter_tree/avl_tree.md
      - 小结: chapter_data_structure/chapter_tree/summary.md
    - 堆:
      - 堆: chapter_data_structure/chapter_heap/heap.md
      - 建堆操作 *: chapter_data_structure/chapter_heap/build_heap.md
      - 小结: chapter_data_structure/chapter_heap/summary.md
  - 图论:
    - 图: chapter_graph/graph.md
    - 图基础操作: chapter_graph/graph_operations.md
    - 图的遍历: chapter_graph/graph_traversal.md
    - 小结: chapter_graph/summary.md
  
